// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoringAPI.Data;

namespace StoringAPI.Data.Migrations
{
    [DbContext(typeof(HohContext))]
    [Migration("20200823100815_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StoringAPI.Data.SurveyResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AfterLife")
                        .HasColumnType("int");

                    b.Property<Guid>("FrontUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HeavenPoints")
                        .HasColumnType("int");

                    b.Property<int>("HelPoints")
                        .HasColumnType("int");

                    b.Property<int>("HellPoints")
                        .HasColumnType("int");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<int>("Step")
                        .HasColumnType("int");

                    b.Property<int>("ValhallaPoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FrontUuid")
                        .IsUnique();

                    b.ToTable("SurveyResults");
                });

            modelBuilder.Entity("StoringAPI.Data.SurveyResult", b =>
                {
                    b.OwnsOne("StoringAPI.Models.EnvyModel", "Envy", b1 =>
                        {
                            b1.Property<int>("SurveyResultId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<bool>("EnvyToFriend")
                                .HasColumnType("bit");

                            b1.Property<bool>("ProudOfTheLeader")
                                .HasColumnType("bit");

                            b1.Property<bool>("TryToAnnoy")
                                .HasColumnType("bit");

                            b1.HasKey("SurveyResultId");

                            b1.ToTable("SurveyResults");

                            b1.WithOwner()
                                .HasForeignKey("SurveyResultId");
                        });

                    b.OwnsOne("StoringAPI.Models.GluttonyModel", "Gluttony", b1 =>
                        {
                            b1.Property<int>("SurveyResultId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<bool>("Cookies")
                                .HasColumnType("bit");

                            b1.Property<int>("EatingInDay")
                                .HasColumnType("int");

                            b1.Property<bool>("FastFood")
                                .HasColumnType("bit");

                            b1.Property<int>("MostImportantType")
                                .HasColumnType("int");

                            b1.HasKey("SurveyResultId");

                            b1.ToTable("SurveyResults");

                            b1.WithOwner()
                                .HasForeignKey("SurveyResultId");
                        });

                    b.OwnsOne("StoringAPI.Models.GreedModel", "Greed", b1 =>
                        {
                            b1.Property<int>("SurveyResultId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<bool>("AreYouDragon")
                                .HasColumnType("bit");

                            b1.Property<bool>("CanLendMoney")
                                .HasColumnType("bit");

                            b1.Property<int>("Collections")
                                .HasColumnType("int");

                            b1.Property<bool>("Hoard")
                                .HasColumnType("bit");

                            b1.Property<bool>("TouchebleCollection")
                                .HasColumnType("bit");

                            b1.HasKey("SurveyResultId");

                            b1.ToTable("SurveyResults");

                            b1.WithOwner()
                                .HasForeignKey("SurveyResultId");
                        });

                    b.OwnsOne("StoringAPI.Models.LustModel", "Lust", b1 =>
                        {
                            b1.Property<int>("SurveyResultId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("HowManyPartners")
                                .HasColumnType("int");

                            b1.Property<bool>("IllegalActions")
                                .HasColumnType("bit");

                            b1.Property<bool>("PassionDream")
                                .HasColumnType("bit");

                            b1.Property<bool>("WasInOrgies")
                                .HasColumnType("bit");

                            b1.HasKey("SurveyResultId");

                            b1.ToTable("SurveyResults");

                            b1.WithOwner()
                                .HasForeignKey("SurveyResultId");
                        });

                    b.OwnsOne("StoringAPI.Models.PersonModel", "Person", b1 =>
                        {
                            b1.Property<int>("SurveyResultId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Color")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("DateOfBirth")
                                .HasColumnType("datetime2");

                            b1.Property<int>("Gender")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(50)")
                                .HasMaxLength(50);

                            b1.HasKey("SurveyResultId");

                            b1.ToTable("SurveyResults");

                            b1.WithOwner()
                                .HasForeignKey("SurveyResultId");
                        });

                    b.OwnsOne("StoringAPI.Models.PrideModel", "Pride", b1 =>
                        {
                            b1.Property<int>("SurveyResultId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<bool>("AcceptFail")
                                .HasColumnType("bit");

                            b1.Property<bool>("BetterThanOther")
                                .HasColumnType("bit");

                            b1.Property<int>("WhoFail")
                                .HasColumnType("int");

                            b1.HasKey("SurveyResultId");

                            b1.ToTable("SurveyResults");

                            b1.WithOwner()
                                .HasForeignKey("SurveyResultId");
                        });

                    b.OwnsOne("StoringAPI.Models.SlothModel", "Sloth", b1 =>
                        {
                            b1.Property<int>("SurveyResultId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("LazyDescription")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("PassiveRest")
                                .HasColumnType("bit");

                            b1.Property<int>("ReactionOnAccident")
                                .HasColumnType("int");

                            b1.Property<int>("Servants")
                                .HasColumnType("int");

                            b1.HasKey("SurveyResultId");

                            b1.ToTable("SurveyResults");

                            b1.WithOwner()
                                .HasForeignKey("SurveyResultId");
                        });

                    b.OwnsOne("StoringAPI.Models.WrathModel", "Wrath", b1 =>
                        {
                            b1.Property<int>("SurveyResultId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("BrokenItems")
                                .HasColumnType("int");

                            b1.Property<bool>("EasyToAnger")
                                .HasColumnType("bit");

                            b1.Property<bool>("GodOfWar")
                                .HasColumnType("bit");

                            b1.Property<bool>("TryingToControl")
                                .HasColumnType("bit");

                            b1.HasKey("SurveyResultId");

                            b1.ToTable("SurveyResults");

                            b1.WithOwner()
                                .HasForeignKey("SurveyResultId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
