version: '3.8'

services:
  
  vuespa:
    build:
      args:
        - "BACK_URL=http://localhost:8081"
    environment:
      VUE_APP_BACKEND_URL: "http://localhost:8081"
    ports:
      - "8080:80"

  storingapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - FrontendOrigin=http://localhost:8080
    ports:
      - "8081:80"
      - "4431:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  
  sql:
    ports:
      - "1433:1433"