version: '3.8'

services:

  vuespa:
    image: hoh-front
    build:
      context: ./VueSPA
    depends_on:
      - storingapi


  storingapi:
    image: hoh-back
    build:
      context: .
      dockerfile: StoringAPI/Dockerfile
    depends_on:
      - sql
    environment:
      "ConnectionStrings__DefaultConnection": "Data source=sql;User=sa;Password=Pass@word1;Database=hoh"
      

  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pass@word1"
    